### ISSUE TITLE
Настройка страницы 404

### ISSUE THREAD

**Issue by avtopro** [Tatlex/decoderVIN#2]
Этого не было в требованиях к задаче и мы не считаем это ошибкой, но предусматривать запросы к несуществующим страницам очень желательно. Прямое взаимодействие с адресной строкой это базовая возможность пользователя Веба, и ничто не мешает попытаться зайти на страницу /about, или опечататься в адресе /varia**lb**es, например.

В React Router v6 способ настройки поменялся, он описан в документации: https://reactrouter.com/en/main/start/tutorial#handling-not-found-errors.

Хотя настройка через `<Route path="*" ...>` тоже возможна.

https://github.com/Tatlex/decoderVIN/blob/2a4500326be76a9dcb9f3b6fa46037fac1170d32/src/App.js#L12-L21

**Comment by Tatlex** [comment]
Страница 404 была осуществлена с помощью того же `<BrowserRouter> ` внутри которого мы поместили в `<Routes>`   новый  `<Route/>`  :

`<Route path='*' element={<ErrorPage/>}/>`

 Детальнее со страницей _404 Error_ можно ознакомится по этой [ссылке](https://github.com/Tatlex/decoderVIN/blob/master/src/Components/ErrorPage/ErrorPage.jsx) где можно увидеть содержимое компоненты `<ErrorPage />` а так же [стили](https://github.com/Tatlex/decoderVIN/blob/master/src/Components/ErrorPage/ErrorPage.module.css) которые были применены к данной странице.
